#!/usr/bin/env python3
"""Recompute KSG k=3/4/5 sensitivity for canonical Fig 3 P1--P4."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.feature_selection import mutual_info_regression


REPO = Path(__file__).resolve().parents[1]
DEFAULT_RUN = (
    REPO
    / "analysis_outputs/pm50_reduced_campaign/ARCADE_OUTPUT/ABC_SMC_RF_N1024_pm50/iter_4"
)
DEFAULT_ASSIGNMENTS = REPO / "analysis_outputs/pm50_fig3/canonical_peak_assignments.csv"
DEFAULT_CSV = REPO / "analysis_outputs/pm50_fig3/canonical_mi_k_stability.csv"
DEFAULT_TEX = REPO / "body/extended_data/ed_table_mi_kstability.tex"
DEFAULT_PROVENANCE = REPO / "analysis_outputs/pm50_fig3/canonical_mi_k_stability_provenance.json"
METRICS = ["doub_time", "symmetry", "colony_growth"]
META = {"input_folder", "X_SPACING", "Y_SPACING", "DISTANCE_TO_CENTER"}
DISPLAY = {
    "CELL_VOLUME_MU": "Cell Volume",
    "NECROTIC_FRACTION": "Necrotic Fraction",
    "ACCURACY": "Accuracy",
    "COMPRESSION_TOLERANCE": "Compression Tolerance",
    "SYNTHESIS_DURATION_MU": "Synthesis Duration",
    "BASAL_ENERGY_MU": "Basal Energy",
    "PROLIFERATION_ENERGY_MU": "Proliferation Energy",
    "MIGRATION_ENERGY_MU": "Migration Energy",
    "METABOLIC_PREFERENCE_MU": "Metabolic Preference",
    "CONVERSION_FRACTION_MU": "Conversion Fraction",
    "RATIO_GLUCOSE_PYRUVATE_MU": "Ratio Glucose Pyruvate",
    "LACTATE_RATE_MU": "Lactate Rate",
    "AUTOPHAGY_RATE_MU": "Autophagy Rate",
    "GLUCOSE_UPTAKE_RATE_MU": "Glucose Uptake Rate",
    "ATP_PRODUCTION_RATE_MU": "ATP Production Rate",
    "MIGRATORY_THRESHOLD_MU": "Migratory Threshold",
    "GLUCOSE_CONCENTRATION": "Glucose Concentration",
    "OXYGEN_CONCENTRATION": "Oxygen Concentration",
    "CAPILLARY_DENSITY": "Capillary Density",
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def normalized_profile(params: pd.DataFrame, metrics: pd.DataFrame, k: int) -> dict[str, float]:
    frame = params.merge(metrics[["input_folder", *METRICS]], on="input_folder")
    columns = [
        column
        for column in params.columns
        if column not in META
        and pd.api.types.is_numeric_dtype(params[column])
        and params[column].std() > 0
    ]
    normalized = {column: [] for column in columns}
    for metric in METRICS:
        valid = frame[metric].replace([np.inf, -np.inf], np.nan).dropna().index
        x = frame.loc[valid, columns].fillna(frame[columns].median(numeric_only=True))
        y = frame.loc[valid, metric].to_numpy(float)
        raw = mutual_info_regression(x, y, n_neighbors=k, random_state=42)
        denominator = float(raw.max() - raw.min())
        values = (raw - raw.min()) / denominator if denominator > 0 else np.zeros_like(raw)
        for column, value in zip(columns, values):
            normalized[column].append(float(value))
    return {column: float(np.mean(values)) for column, values in normalized.items()}


def render_tex(rows: pd.DataFrame) -> str:
    lines = [
        "% Generated by analysis_scripts/canonical_pm50_mi_k_stability.py",
        "% Canonical Fig 3 unweighted P1--P4; dominant if Rbar > 0.7.",
        r"\begin{tabular}{llrrrc}",
        r"\hline",
        r"\textbf{Peak} & \textbf{Parameter} & $\bar{R}_\theta^{k=3}$ & $\bar{R}_\theta^{k=4}$ & $\bar{R}_\theta^{k=5}$ & \textbf{Core} \\",
        r"\hline",
    ]
    previous_peak = None
    for row in rows.itertuples(index=False):
        peak = f"P{row.peak}" if row.peak != previous_peak else ""
        core = r"$\checkmark$" if row.core else ""
        lines.append(
            f"{peak} & {row.parameter_display} & {row.k3:.2f} & {row.k4:.2f} & {row.k5:.2f} & {core} \\\\"
        )
        previous_peak = row.peak
    lines.extend([r"\hline", r"\end{tabular}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run", type=Path, default=DEFAULT_RUN)
    parser.add_argument("--assignments", type=Path, default=DEFAULT_ASSIGNMENTS)
    parser.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    parser.add_argument("--tex", type=Path, default=DEFAULT_TEX)
    parser.add_argument("--provenance", type=Path, default=DEFAULT_PROVENANCE)
    args = parser.parse_args()

    params_path = args.run / "all_param_df.csv"
    metrics_path = args.run / "final_metrics_seed.csv"
    params = pd.read_csv(params_path)
    metrics = pd.read_csv(metrics_path)
    assignments = pd.read_csv(args.assignments)
    if assignments.input_folder.tolist() != params.input_folder.astype(str).tolist():
        raise RuntimeError("assignment rows are not aligned to parent parameter rows")

    rows = []
    for peak in range(1, 5):
        selected = params.loc[assignments.peak.to_numpy(int) == peak].reset_index(drop=True)
        selected_metrics = metrics[metrics.input_folder.isin(set(selected.input_folder))].reset_index(drop=True)
        profiles = {k: normalized_profile(selected, selected_metrics, k) for k in (3, 4, 5)}
        for parameter in profiles[3]:
            values = [profiles[k][parameter] for k in (3, 4, 5)]
            if max(values) > 0.7:
                rows.append(
                    {
                        "peak": peak,
                        "parameter": parameter,
                        "parameter_display": DISPLAY[parameter],
                        "k3": values[0],
                        "k4": values[1],
                        "k5": values[2],
                        "core": all(value > 0.7 for value in values),
                    }
                )
    result = pd.DataFrame(rows).sort_values(["peak", "k3"], ascending=[True, False])
    args.csv.parent.mkdir(parents=True, exist_ok=True)
    result.to_csv(args.csv, index=False)
    args.tex.write_text(render_tex(result), encoding="utf-8")
    provenance = {
        "version": 1,
        "assignment_convention": "frozen Fig 3 unweighted PCA/KDE",
        "assignments": str(args.assignments.relative_to(REPO)),
        "assignments_sha256": sha256(args.assignments),
        "params": str(params_path.relative_to(REPO)),
        "params_sha256": sha256(params_path),
        "metrics": str(metrics_path.relative_to(REPO)),
        "metrics_sha256": sha256(metrics_path),
        "ksg_neighbor_counts": [3, 4, 5],
        "random_state": 42,
        "normalization": "per metric min-max across parameters within canonical subset",
        "display_cutoff": "> 0.7",
        "csv": str(args.csv.relative_to(REPO)),
        "csv_sha256": sha256(args.csv),
        "tex": str(args.tex.relative_to(REPO)),
        "tex_sha256": sha256(args.tex),
        "script": str(Path(__file__).relative_to(REPO)),
        "script_sha256": sha256(Path(__file__)),
        "command": "python analysis_scripts/canonical_pm50_mi_k_stability.py",
    }
    args.provenance.write_text(json.dumps(provenance, indent=2) + "\n", encoding="utf-8")
    print(result.to_string(index=False))


if __name__ == "__main__":
    main()
